### ISSUE TITLE
SambagTimePickerViewController: Meridian not showing the "AM" option

### ISSUE THREAD

**Issue by Travloper** [mownier/sambag#14]
Code - 

```
var theme: SambagTheme = .light

let vc = SambagTimePickerViewController()
vc.theme = theme
vc.delegate = self
present(vc, animated: true, completion: nil)
```

-----------------------

Output : 

![simulator_screenshot_84EEBC50-3D91-4AB0-8C83-A9E11640376E](https://user-images.githubusercontent.com/34119588/110197792-f6176800-7e73-11eb-81e7-7067cef0c9d8.png)

**Comment by AbdulJaf** [comment]
Having same issue. Is it cleared?

**Comment by mownier** [comment]
Use version 1.1.0

**Comment by AbdulJaf** [comment]
What version? there was no pod file used in this project and why did you close the issue without even telling a reasonable answer?

**Comment by mownier** [comment]
In your project's Podfile
```
 pod 'Sambag', '1.1.0'
```
