### ISSUE TITLE
iPad and Other Orientations

### ISSUE THREAD

**Issue by chathuralakmal** [mownier/sambag#3]
I loved the library. but i couldnt use this because it does not support ipad screens. layout is messy.

**Comment by mownier** [comment]
Resolved by commit a1553f7687af669c5b815da73a320c6eb003eaae.

**Comment by chathuralakmal** [comment]
I have tried in my ipad.when i click and open the picker first time it doesnt work correctly, but if i change the orientation it gets corrected.

**Comment by mownier** [comment]
Did you update the pod to version 1.0.1? It is working fine when I tested it in iOS 11 iPad simulators.
