### ISSUE TITLE
Customization Properties

### ISSUE THREAD

**Issue by ZacharyKhan** [mownier/sambag#4]
It would be super convenient to have public properties associated with the controllers that allow you to customize colors and other preferences. 

For example, regardless of the theme you use, the color of the underline for the pickers is by default blue and cannot be changed unless the Sambag library itself is modified, which is not ideal for those of us who use dependency managers such as Cocoapods. 

If I find some time this weekend, I will try to fork the repo and submit a PR with these changes.

**Comment by mownier** [comment]
Actually, you can change that default blue-ish color. 

```swift
var attrib = SambagThemeAttribute()
attrib.stripColor = UIColor.brown // This is the one you are looking for
attrib.titleTextColor = UIColor.green
let vc = SambagDatePickerViewController()
let theme: SambagTheme = .custom(attrib)
vc.theme = theme
vc.delegate = self
present(vc, animated: true, completion: nil)
```

I think that exposing and making those properties public would violate the open/closed principle. The framework will be too open such that there will be a high number of possible modifications. I prefer the current encapsulation of the properties.
