### ISSUE TITLE
Design Problem when i just downloaded

### ISSUE THREAD

**Issue by saileshgb** [mownier/sambag#7]
There is no proper alignment for the month and year view.

![simulator screen shot - iphone 8 - 2018-06-28 at 12 01 47](https://user-images.githubusercontent.com/21154745/42017023-42340568-7acb-11e8-97ce-5d364317b31d.png)

**Comment by taier** [comment]
fix https://github.com/taier/sambag/commit/6cf685c31f3209bfd126c395f4525483fce7c951

**Comment by taier** [comment]
@mownier vote to close
