### ISSUE TITLE
UI Issue

### ISSUE THREAD

**Issue by Siddharth14291** [mownier/sambag#8]
Major UI Issue...
![simulator screen shot - iphone 5s - 2018-07-16 at 13 02 42](https://user-images.githubusercontent.com/16458979/42747134-af8857be-88f8-11e8-9fbb-2fe0b5e16a6b.png)
![simulator screen shot - iphone 5s - 2018-07-16 at 13 03 01](https://user-images.githubusercontent.com/16458979/42747135-afb2ccd8-88f8-11e8-9940-ff233e16d9e4.png)

**Comment by taier** [comment]
fix https://github.com/taier/sambag/commit/6cf685c31f3209bfd126c395f4525483fce7c951

**Comment by taier** [comment]
@mownier vote to close
